/**
 * vinext/pwa — Progressive Web App module
 *
 * Generates manifest.json and service worker templates from configuration.
 * Framework-level — any Vinext project can enable PWA with minimal config.
 *
 * Config in next.config.js:
 *   pwa: {
 *     name: "My App",
 *     shortName: "App",
 *     themeColor: "#000000",
 *     backgroundColor: "#ffffff",
 *     display: "standalone",
 *     icons: [{ src: "/icon-192.png", sizes: "192x192", type: "image/png" }],
 *   }
 */

export interface PWAIcon {
    src: string;
    sizes: string;
    type?: string;
    purpose?: "any" | "maskable" | "monochrome";
}

export interface PWAConfig {
    /** Full app name */
    name: string;
    /** Short name for home screen */
    shortName?: string;
    /** App description */
    description?: string;
    /** Start URL (default "/") */
    startUrl?: string;
    /** Display mode */
    display?: "fullscreen" | "standalone" | "minimal-ui" | "browser";
    /** Orientation */
    orientation?: "any" | "natural" | "landscape" | "portrait";
    /** Theme color */
    themeColor?: string;
    /** Background color for splash screen */
    backgroundColor?: string;
    /** Array of icon definitions */
    icons?: PWAIcon[];
    /** App scope */
    scope?: string;
    /** Language */
    lang?: string;
    /** Categories */
    categories?: string[];
    /** Shortcuts */
    shortcuts?: Array<{
        name: string;
        url: string;
        description?: string;
        icons?: PWAIcon[];
    }>;
}

/**
 * Generate manifest.json content from configuration.
 */
export function generateManifest(config: PWAConfig): string {
    const manifest: Record<string, unknown> = {
        name: config.name,
        short_name: config.shortName ?? config.name,
        start_url: config.startUrl ?? "/",
        display: config.display ?? "standalone",
        background_color: config.backgroundColor ?? "#ffffff",
        theme_color: config.themeColor ?? "#000000",
    };

    if (config.description) manifest.description = config.description;
    if (config.orientation) manifest.orientation = config.orientation;
    if (config.scope) manifest.scope = config.scope;
    if (config.lang) manifest.lang = config.lang;
    if (config.categories) manifest.categories = config.categories;

    if (config.icons?.length) {
        manifest.icons = config.icons.map((icon) => ({
            src: icon.src,
            sizes: icon.sizes,
            type: icon.type ?? "image/png",
            ...(icon.purpose ? { purpose: icon.purpose } : {}),
        }));
    }

    if (config.shortcuts?.length) {
        manifest.shortcuts = config.shortcuts.map((s) => ({
            name: s.name,
            url: s.url,
            ...(s.description ? { description: s.description } : {}),
            ...(s.icons ? { icons: s.icons } : {}),
        }));
    }

    return JSON.stringify(manifest, null, 2);
}

/**
 * Generate a service worker script with configurable caching strategies.
 *
 * Strategies:
 * - Static assets: Cache-First (hashed filenames = immutable)
 * - API calls: Network-First (always fresh, fallback to cache)
 * - Pages: Stale-While-Revalidate (fast + eventually consistent)
 */
export function generateServiceWorker(options: {
    /** Cache name prefix */
    cacheName?: string;
    /** Paths to precache */
    precache?: string[];
    /** Offline fallback page */
    offlineFallback?: string;
    /** Max cache age in seconds */
    maxAge?: number;
} = {}): string {
    const {
        cacheName = "vinext-cache-v1",
        precache = ["/", "/offline"],
        offlineFallback = "/offline",
        maxAge = 86400,
    } = options;

    return `// Generated by Vinext PWA Module (TichPhong OS)
// Cache name: ${cacheName}

const CACHE_NAME = "${cacheName}";
const PRECACHE_URLS = ${JSON.stringify(precache)};
const OFFLINE_FALLBACK = "${offlineFallback}";
const MAX_AGE = ${maxAge} * 1000;

// Install: precache essential assets
self.addEventListener("install", (event) => {
  event.waitUntil(
    caches.open(CACHE_NAME).then((cache) => cache.addAll(PRECACHE_URLS))
  );
  self.skipWaiting();
});

// Activate: clean up old caches
self.addEventListener("activate", (event) => {
  event.waitUntil(
    caches.keys().then((keys) =>
      Promise.all(keys.filter((k) => k !== CACHE_NAME).map((k) => caches.delete(k)))
    )
  );
  self.clients.claim();
});

// Fetch: apply caching strategies
self.addEventListener("fetch", (event) => {
  const { request } = event;
  const url = new URL(request.url);

  // Skip non-GET and cross-origin
  if (request.method !== "GET" || url.origin !== self.location.origin) return;

  // API routes: Network-First
  if (url.pathname.startsWith("/api/")) {
    event.respondWith(
      fetch(request)
        .then((response) => {
          const clone = response.clone();
          caches.open(CACHE_NAME).then((cache) => cache.put(request, clone));
          return response;
        })
        .catch(() => caches.match(request))
    );
    return;
  }

  // Static assets (fingerprinted): Cache-First
  if (url.pathname.match(/\\/assets\\/.*\\.[a-f0-9]{8}\\./)) {
    event.respondWith(
      caches.match(request).then((cached) => cached || fetch(request).then((response) => {
        const clone = response.clone();
        caches.open(CACHE_NAME).then((cache) => cache.put(request, clone));
        return response;
      }))
    );
    return;
  }

  // Pages: Stale-While-Revalidate
  event.respondWith(
    caches.match(request).then((cached) => {
      const networkFetch = fetch(request)
        .then((response) => {
          const clone = response.clone();
          caches.open(CACHE_NAME).then((cache) => cache.put(request, clone));
          return response;
        })
        .catch(() => {
          if (request.mode === "navigate") return caches.match(OFFLINE_FALLBACK);
          return undefined;
        });
      return cached || networkFetch;
    })
  );
});
`;
}
